% Method: settings
%  -Default settings for graphical user interface

function obj = settings(obj, varargin)

% Determine system information
obj.options.os = computer;
obj.options.matlab_version = version('-release');
obj.options.gui_version = 1.0;

% Determine screen information
obj.options.screensize = get(0, 'ScreenSize');
obj.options.screenresolution = get(0, 'ScreenPixelsPerInch');

% Set variables
backgroundcolor = [0.98, 0.98, 0.98];
fontsize = 11;

% Set figure defaults
set(0, ...
    'DefaultFigureColor', [0.99, 0.99, 0.99],...
    'DefaultFigureDockControls', 'off',...
    'DefaultFigureMenuBar', 'none',...
    'DefaultFigureNumberTitle', 'off',...
    'DefaultFigureRenderer', 'opengl',...
    'DefaultFigureResize', 'on',...
    'DefaultFigureUnits', 'pixels');

% Set table defaults
set(0, ...
    'DefaultUITableBackgroundColor', [0.99, 0.99, 0.99; 0.95, 0.95, 0.95],...
    'DefaultUITableFontName', 'SansSerif',...
    'DefaultUITableFontSize', fontsize,...
    'DefaultUITableFontUnits', 'points',...
    'DefaultUITableFontWeight', 'light',...
    'DefaultUITableForegroundColor', [0.0, 0.0, 0.0],...
    'DefaultUITableRearrangeableColumns', 'off',...
    'DefaultUITableRowName', [],...
    'DefaultUITableRowStriping', 'on',...
    'DefaultUITableUnits', 'normalized');

% Set axes defaults
set(0, ...
    'DefaultAxesBox', 'on',...
    'DefaultAxesColor', [1.0, 1.0, 1.0],...
    'DefaultAxesDrawMode', 'fast',...
    'DefaultAxesFontName', 'Helvetica',...
    'DefaultAxesFontSize', fontsize,...
    'DefaultAxesFontUnits', 'points',...
    'DefaultAxesFontWeight', 'normal',...
    'DefaultAxesLayer', 'top',...
    'DefaultAxesLineWidth', 2.5,...
    'DefaultAxesNextPlot', 'add',...
    'DefaultAxesTickDir', 'out',...
    'DefaultAxesTickLength', [0.0015, 0.0005],...
    'DefaultAxesUnits', 'normalized',...
    'DefaultAxesXColor', [0.1, 0.1, 0.1],...
    'DefaultAxesYColor', [0.1, 0.1, 0.1],...
    'DefaultAxesZColor', [0.6, 0.6, 0.6],...
    'DefaultAxesXGrid', 'off',...
    'DefaultAxesXLimMode', 'manual',...
    'DefaultAxesYLimMode', 'manual',...
    'DefaultAxesZLimMode', 'manual',...
    'DefaultAxesXTickMode', 'auto',...
    'DefaultAxesXTickLabelMode', 'auto',...
    'DefaultAxesYTick', [],...
    'DefaultAxesYTickLabel', [],...
    'DefaultAxesYTickLabelMode', 'manual',...
    'DefaultAxesZTick', [],...
    'DefaultAxesZTickLabel', [],...
    'DefaultAxesZTickLabelMode', 'manual');

% Set control defaults
set(0, ...
    'DefaultUIControlBackgroundColor', backgroundcolor,...
    'DefaultUIControlFontName', 'SansSerif',...
    'DefaultUIControlFontSize', fontsize,...
    'DefaultUIControlFontUnits', 'points',...
    'DefaultUIControlFontWeight', 'light',...
    'DefaultUIControlForegroundColor', [0.0, 0.0, 0.0],...
    'DefaultUIControlHorizontalAlignment', 'center',...
    'DefaultUIControlUnits', 'normalized');

% Set panel defaults
set(0, ...
    'DefaultUIPanelBackgroundColor', backgroundcolor,...
    'DefaultUIPanelBorderType', 'line',...
    'DefaultUIPanelBorderWidth', 2.5,...
    'DefaultUIPanelFontName', 'SansSerif',...
    'DefaultUIPanelFontSize', fontsize,...
    'DefaultUIPanelFontUnits', 'points',...
    'DefaultUIPanelFontWeight', 'normal',...
    'DefaultUIPanelForegroundColor', [0.0, 0.0, 0.0],...
    'DefaultUIPanelHighlightColor', [0.0, 0.0, 0.0],...
    'DefaultUIPanelUnits', 'normalized');

% Disable command line warnings
warning off all

end